<?php

namespace Database\Seeders;

use App\Models\Lisali;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use function Ramsey\Uuid\v1;

class LisaliSeeder extends Seeder
{
    
    public function run(): void
    {
        $lisalis = [
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 1, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 2, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 3, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 4, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 5, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 6, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 7, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 8, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 9, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 10, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 11, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 12, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 13, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 14, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 15, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 16, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 17, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 18, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 19, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 20, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 21, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 22, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 23, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 24, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 25, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 26, 'f_registro' => now()],
            ['nombre' => 'lista regular','alimento_id' => 1,'producto_id' => 27, 'f_registro' => now()],

            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 1, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 2, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 3, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 4, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 5, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 6, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 7, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 8, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 9, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 10, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 11, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 12, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 13, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 14, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 15, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 16, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 17, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 18, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 19, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 20, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 21, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 22, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 23, 'f_registro' => now()],
            ['nombre' => 'lista vegetariano','alimento_id' => 2,'producto_id' => 24, 'f_registro' => now()],

            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 1, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 2, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 3, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 4, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 5, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 6, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 7, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 8, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 9, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 10, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 11, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 14, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 16, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 17, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 19, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 20, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 21, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 18, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 19, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 20, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 21, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 22, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 23, 'f_registro' => now()],
            ['nombre' => 'lista vegano','alimento_id' => 3,'producto_id' => 24, 'f_registro' => now()],

            ['nombre' => 'lista kosher','alimento_id' => 4,'producto_id' => 2, 'f_registro' => now()],
            ['nombre' => 'lista kosher','alimento_id' => 4,'producto_id' => 3, 'f_registro' => now()],
            ['nombre' => 'lista kosher','alimento_id' => 4,'producto_id' => 4, 'f_registro' => now()],
            ['nombre' => 'lista kosher','alimento_id' => 4,'producto_id' => 5, 'f_registro' => now()],
            ['nombre' => 'lista kosher','alimento_id' => 4,'producto_id' => 7, 'f_registro' => now()],
            ['nombre' => 'lista kosher','alimento_id' => 4,'producto_id' => 8, 'f_registro' => now()],
            ['nombre' => 'lista kosher','alimento_id' => 4,'producto_id' => 9, 'f_registro' => now()],
            ['nombre' => 'lista kosher','alimento_id' => 4,'producto_id' => 11, 'f_registro' => now()],
            ['nombre' => 'lista kosher','alimento_id' => 4,'producto_id' => 12, 'f_registro' => now()],
            ['nombre' => 'lista kosher','alimento_id' => 4,'producto_id' => 13, 'f_registro' => now()],
            ['nombre' => 'lista kosher','alimento_id' => 4,'producto_id' => 14, 'f_registro' => now()],
            ['nombre' => 'lista kosher','alimento_id' => 4,'producto_id' => 15, 'f_registro' => now()],
            ['nombre' => 'lista kosher','alimento_id' => 4,'producto_id' => 16, 'f_registro' => now()],
            ['nombre' => 'lista kosher','alimento_id' => 4,'producto_id' => 18, 'f_registro' => now()],
            ['nombre' => 'lista kosher','alimento_id' => 4,'producto_id' => 19, 'f_registro' => now()],
            ['nombre' => 'lista kosher','alimento_id' => 4,'producto_id' => 20, 'f_registro' => now()],
            ['nombre' => 'lista kosher','alimento_id' => 4,'producto_id' => 21, 'f_registro' => now()],
            ['nombre' => 'lista kosher','alimento_id' => 4,'producto_id' => 22, 'f_registro' => now()],
            ['nombre' => 'lista kosher','alimento_id' => 4,'producto_id' => 24, 'f_registro' => now()],

            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 1, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 3, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 4, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 5, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 6, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 8, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 9, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 10, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 12, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 13, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 14, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 15, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 16, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 17, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 18, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 19, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 20, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 21, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 22, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 23, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 24, 'f_registro' => now()],
            ['nombre' => 'lista libre de gluten','alimento_id' => 5,'producto_id' => 26, 'f_registro' => now()],

            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 1, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 3, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 4, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 5, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 6, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 8, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 9, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 10, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 12, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 13, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 14, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 15, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 16, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 17, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 18, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 19, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 20, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 21, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 22, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 23, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 24, 'f_registro' => now()],
            ['nombre' => 'lista ciliaco','alimento_id' => 6,'producto_id' => 26, 'f_registro' => now()],


        ];

        Lisali::insert($lisalis);
    }
}
