<?php

namespace Database\Seeders;

use App\Models\Tours;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ToursSeeder extends Seeder
{

    public function run(): void
    {
        $tours = [

            ['precio' => 360,'precioprivado' => 560,  'ndia' => 1, 'dificultad' => 'Moderada', 'hinicio' => '07:00 ', 'hfin' => '18:00 ', 'recomendaciones' => 'Llevar agua y protector solar.', 'llevar' => 'Agua, comida ligera y zapatos cómodos.', 'destino_id' => 1, 'lisali_id' => 1, 'transporte_id' => 1, 'hospedaje_id' => 1, 'obs_include_id' => 1, 'obs_noinclude_id' => 1, 'foto_tour_id' => 1, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 2, 'dificultad' => 'Alta', 'hinicio' => '07:30 ', 'hfin' => '19:30 ', 'recomendaciones' => 'Llevar ropa abrigada y equipo de montañismo.', 'llevar' => 'Comida energética y botiquín básico.', 'destino_id' => 2, 'lisali_id' => 1, 'transporte_id' => 2, 'hospedaje_id' => 2, 'obs_include_id' => 2, 'obs_noinclude_id' => 2, 'foto_tour_id' => 2, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 2, 'dificultad' => 'Moderada', 'hinicio' => '07:00 ', 'hfin' => '20:00 ', 'recomendaciones' => 'Llevar agua y protector solar.', 'llevar' => 'Agua, comida ligera y zapatos cómodos.', 'destino_id' => 3, 'lisali_id' => 1, 'transporte_id' => 3, 'hospedaje_id' => 3, 'obs_include_id' => 3, 'obs_noinclude_id' => 3, 'foto_tour_id' => 3, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 1, 'dificultad' => 'Moderada', 'hinicio' => '07:00 ', 'hfin' => '16:00 ', 'recomendaciones' => 'Llevar agua y protector solar.', 'llevar' => 'Agua, comida ligera y zapatos cómodos.', 'destino_id' => 4, 'lisali_id' => 1, 'transporte_id' => 4, 'hospedaje_id' => 4, 'obs_include_id' => 4, 'obs_noinclude_id' => 4, 'foto_tour_id' => 4, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 1, 'dificultad' => 'Alta', 'hinicio' => '07:30 ', 'hfin' => '16:30 ', 'recomendaciones' => 'Llevar ropa abrigada y equipo de montañismo.', 'llevar' => 'Comida energética y botiquín básico.', 'destino_id' => 5, 'lisali_id' => 1, 'transporte_id' => 5, 'hospedaje_id' => 5, 'obs_include_id' => 1, 'obs_noinclude_id' => 1, 'foto_tour_id' => 5, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 2, 'dificultad' => 'Moderada', 'hinicio' => '07:00 ', 'hfin' => '15:00 ', 'recomendaciones' => 'Llevar agua y protector solar.', 'llevar' => 'Agua, comida ligera y zapatos cómodos.', 'destino_id' => 6, 'lisali_id' => 1, 'transporte_id' => 6, 'hospedaje_id' => 6, 'obs_include_id' => 2, 'obs_noinclude_id' => 2, 'foto_tour_id' => 6, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 1, 'dificultad' => 'Moderada', 'hinicio' => '07:00 ', 'hfin' => '19:00 ', 'recomendaciones' => 'Llevar agua y protector solar.', 'llevar' => 'Agua, comida ligera y zapatos cómodos.', 'destino_id' => 7, 'lisali_id' => 1, 'transporte_id' => 7, 'hospedaje_id' => 7, 'obs_include_id' => 3, 'obs_noinclude_id' => 3, 'foto_tour_id' => 7, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 2, 'dificultad' => 'Alta', 'hinicio' => '07:30 ', 'hfin' => '21:30 ', 'recomendaciones' => 'Llevar ropa abrigada y equipo de montañismo.', 'llevar' => 'Comida energética y botiquín básico.', 'destino_id' => 8, 'lisali_id' => 1, 'transporte_id' => 8, 'hospedaje_id' => 1, 'obs_include_id' => 4, 'obs_noinclude_id' => 4, 'foto_tour_id' => 8, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 2, 'dificultad' => 'Moderada', 'hinicio' => '07:00 ', 'hfin' => '18:00 ', 'recomendaciones' => 'Llevar agua y protector solar.', 'llevar' => 'Agua, comida ligera y zapatos cómodos.', 'destino_id' => 9, 'lisali_id' => 1, 'transporte_id' => 1, 'hospedaje_id' => 2, 'obs_include_id' => 1, 'obs_noinclude_id' => 1, 'foto_tour_id' => 9, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 1, 'dificultad' => 'Moderada', 'hinicio' => '07:00 ', 'hfin' => '17:00 ', 'recomendaciones' => 'Llevar agua y protector solar.', 'llevar' => 'Agua, comida ligera y zapatos cómodos.', 'destino_id' => 10, 'lisali_id' => 1, 'transporte_id' => 1, 'hospedaje_id' => 1, 'obs_include_id' => 1, 'obs_noinclude_id' => 1, 'foto_tour_id' => 10, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 1, 'dificultad' => 'Alta', 'hinicio' => '07:30 ', 'hfin' => '18:30 ', 'recomendaciones' => 'Llevar ropa abrigada y equipo de montañismo.', 'llevar' => 'Comida energética y botiquín básico.', 'destino_id' => 11, 'lisali_id' => 1, 'transporte_id' => 1, 'hospedaje_id' => 1, 'obs_include_id' => 1, 'obs_noinclude_id' => 1, 'foto_tour_id' => 11, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 2, 'dificultad' => 'Moderada', 'hinicio' => '07:00 ', 'hfin' => '19:00 ', 'recomendaciones' => 'Llevar agua y protector solar.', 'llevar' => 'Agua, comida ligera y zapatos cómodos.', 'destino_id' => 12, 'lisali_id' => 1, 'transporte_id' => 2, 'hospedaje_id' => 1, 'obs_include_id' => 2, 'obs_noinclude_id' => 2, 'foto_tour_id' => 12, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 2, 'dificultad' => 'Alta', 'hinicio' => '07:30 ', 'hfin' => '20:30', 'recomendaciones' => 'Llevar ropa abrigada y equipo de montañismo.', 'llevar' => 'Comida energética y botiquín básico.', 'destino_id' => 12, 'lisali_id' => 1, 'transporte_id' => 2, 'hospedaje_id' => 2, 'obs_include_id' => 1, 'obs_noinclude_id' => 2, 'foto_tour_id' => 12, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 1, 'dificultad' => 'Moderada', 'hinicio' => '07:00 ', 'hfin' => '22:00 ', 'recomendaciones' => 'Llevar agua y protector solar.', 'llevar' => 'Agua, comida ligera y zapatos cómodos.', 'destino_id' => 13, 'lisali_id' => 1, 'transporte_id' => 3, 'hospedaje_id' => 3, 'obs_include_id' => 1, 'obs_noinclude_id' => 3, 'foto_tour_id' => 13, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 1, 'dificultad' => 'Alta', 'hinicio' => '07:30 ', 'hfin' => '18:30 ', 'recomendaciones' => 'Llevar ropa abrigada y equipo de montañismo.', 'llevar' => 'Comida energética y botiquín básico.', 'destino_id' => 14, 'lisali_id' => 1, 'transporte_id' => 4, 'hospedaje_id' => 4, 'obs_include_id' => 4, 'obs_noinclude_id' => 4, 'foto_tour_id' => 14, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 1, 'dificultad' => 'Moderada', 'hinicio' => '07:00 ', 'hfin' => '20:00 ', 'recomendaciones' => 'Llevar agua y protector solar.', 'llevar' => 'Agua, comida ligera y zapatos cómodos.', 'destino_id' => 15, 'lisali_id' => 1, 'transporte_id' => 5, 'hospedaje_id' => 5, 'obs_include_id' => 1, 'obs_noinclude_id' => 2, 'foto_tour_id' => 15, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 2, 'dificultad' => 'Alta', 'hinicio' => '07:30 ', 'hfin' => '18:30 ', 'recomendaciones' => 'Llevar ropa abrigada y equipo de montañismo.', 'llevar' => 'Comida energética y botiquín básico.', 'destino_id' => 16, 'lisali_id' => 1, 'transporte_id' => 6, 'hospedaje_id' => 6, 'obs_include_id' => 1, 'obs_noinclude_id' => 1, 'foto_tour_id' => 16, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 1, 'dificultad' => 'Moderada', 'hinicio' => '07:00 ', 'hfin' => '19:00 ', 'recomendaciones' => 'Llevar agua y protector solar.', 'llevar' => 'Agua, comida ligera y zapatos cómodos.', 'destino_id' => 17, 'lisali_id' => 1, 'transporte_id' => 7, 'hospedaje_id' => 7, 'obs_include_id' => 1, 'obs_noinclude_id' => 1, 'foto_tour_id' => 17, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 2, 'dificultad' => 'Alta', 'hinicio' => '07:30 ', 'hfin' => '22:30 ', 'recomendaciones' => 'Llevar ropa abrigada y equipo de montañismo.', 'llevar' => 'Comida energética y botiquín básico.', 'destino_id' => 18, 'lisali_id' => 1, 'transporte_id' => 8, 'hospedaje_id' => 1, 'obs_include_id' => 1, 'obs_noinclude_id' => 1, 'foto_tour_id' => 18, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 1, 'dificultad' => 'Moderada', 'hinicio' => '07:00 ', 'hfin' => '17:00 ', 'recomendaciones' => 'Llevar agua y protector solar.', 'llevar' => 'Agua, comida ligera y zapatos cómodos.', 'destino_id' => 19, 'lisali_id' => 1, 'transporte_id' => 1, 'hospedaje_id' => 1, 'obs_include_id' => 1, 'obs_noinclude_id' => 1, 'foto_tour_id' => 19, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 2, 'dificultad' => 'Alta', 'hinicio' => '07:30 ', 'hfin' => '19:30 ', 'recomendaciones' => 'Llevar ropa abrigada y equipo de montañismo.', 'llevar' => 'Comida energética y botiquín básico.', 'destino_id' => 20, 'lisali_id' => 1, 'transporte_id' => 2, 'hospedaje_id' => 2, 'obs_include_id' => 2, 'obs_noinclude_id' => 2, 'foto_tour_id' => 20, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 1, 'dificultad' => 'Moderada', 'hinicio' => '07:00 ', 'hfin' => '18:00 ', 'recomendaciones' => 'Llevar agua y protector solar.', 'llevar' => 'Agua, comida ligera y zapatos cómodos.', 'destino_id' => 21, 'lisali_id' => 1, 'transporte_id' => 2, 'hospedaje_id' => 1, 'obs_include_id' => 2, 'obs_noinclude_id' => 1, 'foto_tour_id' => 21, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 2, 'dificultad' => 'Alta', 'hinicio' => '07:30 ', 'hfin' => '20:30 ', 'recomendaciones' => 'Llevar ropa abrigada y equipo de montañismo.', 'llevar' => 'Comida energética y botiquín básico.', 'destino_id' => 22, 'lisali_id' => 1, 'transporte_id' => 2, 'hospedaje_id' => 2, 'obs_include_id' => 2, 'obs_noinclude_id' => 2, 'foto_tour_id' => 22, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 1, 'dificultad' => 'Moderada', 'hinicio' => '07:00 ', 'hfin' => '19:00 ', 'recomendaciones' => 'Llevar agua y protector solar.', 'llevar' => 'Agua, comida ligera y zapatos cómodos.', 'destino_id' => 23, 'lisali_id' => 1, 'transporte_id' => 3, 'hospedaje_id' => 3, 'obs_include_id' => 3, 'obs_noinclude_id' => 3, 'foto_tour_id' => 23, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 2, 'dificultad' => 'Alta', 'hinicio' => '07:30 ', 'hfin' => '21:30 ', 'recomendaciones' => 'Llevar ropa abrigada y equipo de montañismo.', 'llevar' => 'Comida energética y botiquín básico.', 'destino_id' => 24, 'lisali_id' => 1, 'transporte_id' => 4, 'hospedaje_id' => 4, 'obs_include_id' => 4, 'obs_noinclude_id' => 4, 'foto_tour_id' => 24, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 1, 'dificultad' => 'Moderada', 'hinicio' => '07:00 ', 'hfin' => '23:00 ', 'recomendaciones' => 'Llevar agua y protector solar.', 'llevar' => 'Agua, comida ligera y zapatos cómodos.', 'destino_id' => 25, 'lisali_id' => 1, 'transporte_id' => 5, 'hospedaje_id' => 5, 'obs_include_id' => 2, 'obs_noinclude_id' => 2, 'foto_tour_id' => 25, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 2, 'dificultad' => 'Alta', 'hinicio' => '07:30 ', 'hfin' => '19:30 ', 'recomendaciones' => 'Llevar ropa abrigada y equipo de montañismo.', 'llevar' => 'Comida energética y botiquín básico.', 'destino_id' => 26, 'lisali_id' => 1, 'transporte_id' => 6, 'hospedaje_id' => 6, 'obs_include_id' => 2, 'obs_noinclude_id' => 2, 'foto_tour_id' => 26, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 1, 'dificultad' => 'Moderada', 'hinicio' => '07:00 ', 'hfin' => '20:00 ', 'recomendaciones' => 'Llevar agua y protector solar.', 'llevar' => 'Agua, comida ligera y zapatos cómodos.', 'destino_id' => 27, 'lisali_id' => 1, 'transporte_id' => 7, 'hospedaje_id' => 7, 'obs_include_id' => 2, 'obs_noinclude_id' => 2, 'foto_tour_id' => 27, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 2, 'dificultad' => 'Alta', 'hinicio' => '07:30 ', 'hfin' => '20:30 ', 'recomendaciones' => 'Llevar ropa abrigada y equipo de montañismo.', 'llevar' => 'Comida energética y botiquín básico.', 'destino_id' => 28, 'lisali_id' => 1, 'transporte_id' => 8, 'hospedaje_id' => 3, 'obs_include_id' => 2, 'obs_noinclude_id' => 2, 'foto_tour_id' => 28, 'f_registro' => now()],
            ['precio' => 360,'precioprivado' => 560, 'ndia' => 1, 'dificultad' => 'Moderada', 'hinicio' => '07:00 ', 'hfin' => '20:00 ', 'recomendaciones' => 'Llevar agua y protector solar.', 'llevar' => 'Agua, comida ligera y zapatos cómodos.', 'destino_id' => 29, 'lisali_id' => 1, 'transporte_id' => 2, 'hospedaje_id' => 4, 'obs_include_id' => 2, 'obs_noinclude_id' => 2, 'foto_tour_id' => 29, 'f_registro' => now()],
        ];
         Tours::insert($tours);
    }
}
